// Regression test at the SDK boundary: transfers signed by the Rust runtime
// must be decoded and signature-verified by the JavaScript SDK, which every
// TypeScript facilitator and seller uses. The fixture is generated by
// `cargo run -q -p mandate --example cross_sdk_fixture`; the Rust test
// `fixture_matches_committed_file` keeps it in step with the signer.
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { PublicKey, TokenId, Transaction, TransferTransaction } from "@hiero-ledger/sdk";

interface Case {
  name: string;
  transaction: string;
  legacy_transaction: string;
  fee_payer: string;
  payer: string;
  pay_to: string;
  asset: string;
  amount: number;
  node_account_ids: string[];
  valid_start_seconds: number;
  valid_duration_seconds: number;
}

interface Fixture {
  public_key_der: string;
  cases: Case[];
}

const fixture = JSON.parse(readFileSync(new URL("../fixtures/rust-signed-transfers.json", import.meta.url), "utf8")) as Fixture;
const publicKey = PublicKey.fromString(fixture.public_key_der);

for (const c of fixture.cases) {
  test(`rust-signed ${c.name} transfer decodes and verifies in the javascript sdk`, () => {
    const decoded = Transaction.fromBytes(Buffer.from(c.transaction, "base64"));
    assert.ok(decoded instanceof TransferTransaction, "a TransferTransaction");
    const tx: TransferTransaction = decoded;
    assert.equal(publicKey.verifyTransaction(tx), true, "signature over every body");
    assert.equal(tx.transactionId?.accountId?.toString(), c.fee_payer);
    assert.equal(Math.floor((tx.transactionId?.validStart?.toDate().getTime() ?? 0) / 1000), c.valid_start_seconds);
    assert.equal(tx.transactionValidDuration, c.valid_duration_seconds);
    assert.deepEqual((tx.nodeAccountIds ?? []).map(String), c.node_account_ids);
    if (c.asset === "0.0.0") {
      const hbar = new Map([...tx.hbarTransfers].map(([account, amount]) => [account.toString(), amount.toTinybars().toString()]));
      assert.equal(hbar.get(c.payer), String(-c.amount));
      assert.equal(hbar.get(c.pay_to), String(c.amount));
      assert.equal(tx.tokenTransfers.size, 0);
    } else {
      const token = tx.tokenTransfers.get(TokenId.fromString(c.asset));
      assert.ok(token, "token transfers for the asset");
      const moves = new Map([...token].map(([account, amount]) => [account.toString(), amount.toString()]));
      assert.equal(moves.get(c.payer), String(-c.amount));
      assert.equal(moves.get(c.pay_to), String(c.amount));
      assert.equal(tx.hbarTransfers.size, 0);
    }
  });

  test(`the sdk's raw ${c.name} bytes are still rejected, so the test guards the rewrite`, () => {
    assert.throws(() => Transaction.fromBytes(Buffer.from(c.legacy_transaction, "base64")), /failed to validate transaction bodies/);
  });
}
